"""
Automated Backend Workflow generated by Scratch Visual Engine for test
Strict Grounding & Zero-Hallucination Pipeline
"""

import os
import sys
import json
import logging
from fastapi import APIRouter, Request, HTTPException
from ai_provider import complete_chat

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/ext/test", tags=["test"])

@router.post("/execute")
async def execute_scratch_pipeline(payload: dict):
    """Executes the visual block flow in strictly defined deterministic order."""
    context = dict(payload)
    execution_log = []

    # Step 1: [عند استلام رسالة واتساب]
    phone_number = context.get("phone", context.get("sender", "unknown"))
    incoming_text = context.get("text", context.get("message", ""))
    execution_log.append(f"Received WhatsApp message from {phone_number}: {incoming_text}")

    # Step 2: [صياغة الرد]
    # AI Synthesis: Strict prompt with SQL facts
    system_prompt = "أنت موظف خدمة عملاء محترف في متجرنا. تحدث بـ عامية مصرية.\n"
    system_prompt += "قاعدة بيانات المتجر (حقيقة مطلقة): " + str(context.get("sql_products", "لا توجد منتجات مطابقة")) + "\n"
    system_prompt += "تعليمات صارمة: لا تبتكر أسعاراً من خيالك مطلقاً، والتزم بالأرقام الموجودة في بيانات المتجر أعلاه."
    user_message = context.get("incoming_text", "مرحبا")
    ai_reply = await complete_chat([
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message}
    ])
    context["ai_reply"] = ai_reply
    execution_log.append("Generated grounded customer reply via Omni AI")

    return {
        "status": "success",
        "execution_steps": execution_log,
        "output_context": context
    }
