"""
Automated Backend Workflow generated by Scratch Visual Engine for smart_sales_bot
Strict Grounding & Zero-Hallucination Pipeline
"""

import os
import sys
import json
import logging
from fastapi import APIRouter, Request, HTTPException
from ai_provider import complete_chat

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/ext/smart_sales_bot", tags=["smart_sales_bot"])

import sqlite3
DB_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "market.db")

def query_database(query: str, params: tuple = ()):
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute(query, params)
        rows = cursor.fetchall()
        conn.close()
        return rows
    except Exception as e:
        logger.error(f"SQL Error: {e}")
        return []

@router.post("/execute")
async def execute_scratch_pipeline(payload: dict):
    """Executes the visual block flow in strictly defined deterministic order."""
    context = dict(payload)
    execution_log = []

    # Step 1: [عند استلام رسالة واتساب]
    phone_number = context.get("phone", context.get("sender", "unknown"))
    incoming_text = context.get("text", context.get("message", ""))
    execution_log.append(f"Received WhatsApp message from {phone_number}")

    # Step 2: [بحث دقيق عن السعر في SQL]
    # SQL Grounding: fetch product price & stock
    search_term = context.get("incoming_text", "")
    db_records = query_database("SELECT name, price, stock FROM products WHERE name LIKE ? LIMIT 3", (f"%{search_term}%",))
    context["sql_products"] = db_records
    execution_log.append(f"Grounding SQL: Found {len(db_records)} records")

    # Step 3: [صياغة رد خدمة العملاء]
    # AI Synthesis: Strict prompt with SQL facts
    system_prompt = "أنت موظف خدمة عملاء محترف في متجرنا. تحدث بـ عامية مصرية ودودة ولائقة.\n"
    system_prompt += "قاعدة بيانات المتجر (حقيقة مطلقة): " + str(context.get("sql_products", "لا توجد منتجات مطابقة")) + "\n"
    system_prompt += "تعليمات صارمة: لا تبتكر أسعاراً من خيالك مطلقاً، والتزم بالأرقام الموجودة في بيانات المتجر أعلاه."
    user_message = context.get("incoming_text", "مرحبا")
    ai_reply = complete_chat([
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message}
    ])
    context["ai_reply"] = ai_reply
    execution_log.append("Generated grounded customer reply via Omni AI")

    # Step 4: [إرسال الرد عبر واتساب]
    # Output Action: Send via WhatsApp
    recipient = context.get("phone_number", "unknown")
    message_to_send = context.get("ai_reply", "شكراً لتواصلك معنا")
    execution_log.append("Dispatched reply to WhatsApp: " + str(recipient))

    return {
        "status": "success",
        "execution_steps": execution_log,
        "output_context": context
    }
