"""
Automated Backend Workflow generated by Scratch Visual Engine for test_flow
Strict Grounding & Zero-Hallucination Pipeline
"""

import os
import sys
import json
import logging
from fastapi import APIRouter, Request, HTTPException
from ai_provider import complete_chat

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/ext/test_flow", tags=["test_flow"])

@router.post("/execute")
async def execute_scratch_pipeline(payload: dict):
    """Executes the visual block flow in strictly defined deterministic order."""
    context = dict(payload)
    execution_log = []

    # Step 1: [واتساب]
    phone_number = context.get("phone", context.get("sender", "unknown"))
    incoming_text = context.get("text", context.get("message", ""))
    execution_log.append(f"Received WhatsApp message from {phone_number}: {incoming_text}")

    # Step 2: [كود ترويجي]
    # Custom Step: External Excel / Data Matcher (كود ترويجي)
    excel_path = "products.xlsx"
    if not os.path.exists(excel_path):
        alt_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), excel_path)
        if os.path.exists(alt_path): excel_path = alt_path
        elif os.path.exists("products.xlsx"): excel_path = "products.xlsx"
    incoming_msg = str(context.get("incoming_text", context.get("message", "")))
    matched_row = None
    try:
        import pandas as pd
        df = pd.read_excel(excel_path) if excel_path.endswith((".xlsx", ".xls")) else pd.read_csv(excel_path)
        target_col = "code" if "code" in df.columns else df.columns[0]
        matches = df[df[target_col].astype(str).str.strip().str.lower().apply(lambda c: c in incoming_msg.lower() if c else False)]
        if not matches.empty:
            matched_row = matches.iloc[0].to_dict()
    except Exception as e_exc:
        logger.warning(f"Excel Match error: {e_exc}")
    context["excel_matched_row"] = matched_row
    context["is_matched"] = matched_row is not None
    execution_log.append(f"Excel Match: {'Found matching row in ' + str(excel_path) if matched_row else 'No matching code in ' + str(excel_path)}")

    # Step 3: [إرسال]
    # Output Action: Send via channel
    recipient = context.get("phone_number", context.get("sender_id", "unknown"))
    message_to_send = context.get("ai_reply", "شكراً لتواصلك معنا")
    execution_log.append("Dispatched reply: " + str(recipient))

    return {
        "status": "success",
        "execution_steps": execution_log,
        "output_context": context
    }
